# Generated by Django 5.2.7 on 2025-12-05 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='conteudo',
        ),
        migrations.AddField(
            model_name='post',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='ingredientes',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='modo_preparo',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
